#!/bin/bash

set -Eeuo pipefail

setup_vars() {

}

run() {

}

main() {
    COMMANDS=("run")

    if [[ "${1-}" == "-h" || "${1-}" == "--help" ]]; then
        usage
        return 0
    fi
    
    setup_dir_env
    cd "$_SCRIPT_DIR"
    trap cleanup 1 2 3 6 15 ERR
    
    local x
    for x in "${COMMANDS[@]}"; do
        local cmd="${1-}"
        if [[ "$x" == "${cmd}" ]]; then
            shift
            setup_vars
            ${cmd//-/_} "$@"
            cleanup
            return 0
        fi
    done
    
    usage
    cleanup
    return 1
}

usage() {
    echo "Usage: $0 <command>"
    echo ""
    echo "Commands:"
    echo "${COMMANDS[@]}"
}

setup_dir_env() {
    _WORKING_DIR="$(pwd)"
    local dir="$(dirname "${BASH_SOURCE[0]}")"
    _SCRIPT_DIR="$(cd "${dir}/" && pwd)"
}

cleanup() {
    cd "$_WORKING_DIR"
}

main "$@"
