#!/usr/bin/env bash

set -Eeuo pipefail

vars() {

}

run() {

}

main() {
    setup_dir_env
    cd "$_SCRIPT_DIR"
    trap cleanup 1 2 3 6 15 ERR
    vars

    if [[ "${1-}" == "-h" || "${1-}" == "--help" ]]; then
        usage
        return 0
    elif [[ "$#" < 1 ]]; then usage; exit 1; fi
    local cmd="${1?cmd required}"
    # Process cmd

    usage
    cleanup
    return 1
}

usage() {
    echo "Usage: $0 <command>"
    echo ""
    echo "Commands:"
    echo "${COMMANDS[@]}"
}

setup_dir_env() {
    _WORKING_DIR="$(pwd)"
    local dir="$(dirname "${BASH_SOURCE[0]}")"
    _SCRIPT_DIR="$(cd "$dir/" && pwd)"
}

cleanup() {
    cd "$_WORKING_DIR"
}

main "$@"
