#!/bin/bash

setup_vars() {

}

main() {

}

run() {
    ensure_script_dir
    set_trap
    cd "$_SPWD"
    if [[ -z "$@" ]]; then
        main "$@"
    else 
        eval "$@"
    fi;
    cleanup
}

ensure_script_dir() {
    _OPWD="$(pwd)"
    local dir="$(dirname "${BASH_SOURCE[0]}")"
    _SPWD="$( cd "${dir}/" && pwd )"
}

set_trap() {
    set -Eeuo pipefail
    trap cleanup 1 2 3 6 15 ERR
}

cleanup() {
    cd "$_OPWD"
}

run "$@"