theme = "plain"
icons = "awesome"

#[[block]]
#block = "xrandr"
#icons = true
#resolution = true
#interval = 2

[[block]]
block = "disk_space"
path = "/"
alias = ""
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
show_percentage = false

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{min}-{max}° avg:{average}°"

[[block]]
block = "load"
interval = 10
format = "{1m} {5m}"

[[block]]
block = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 101
critical_mem = 95
critical_swap = 101

[[block]]
block = "cpu"
interval = 2
frequency = true

[[block]]
block = "net"
device = "wlp5s0"
ssid = true
ip = false
bitrate = false
speed_up = false
speed_down = false
graph_up = false
interval = 5


[[block]]
device = "BAT1"
block = "battery"
interval = 5
format = "{percentage}% {time}"

#[[block]]
# 
# This thing currently cases very high cpu, and gets very chatty 
# with the dbus.
#  
#block = "music"
#player = "audacious"
#buttons = ["prev", "play", "next"]

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 1
format = "%a %b %d | %r"
